trigger: none

pool:
  vmImage: 'ubuntu-latest'
  
strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_10_x:
      node_version: 10.x
      
steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Build and Test'



